### ISSUE TITLE
Allow hiding of typewriter keys without hiding the octave and keymap selectors

### ISSUE THREAD

**Issue by kagu** [kunquat/kunquat#546]

**Comment by cyberixae** [comment]
Sounds weird. What is the goal behind this?

**Comment by kagu** [comment]
Selecting octave (and seeing which octave is selected) is a common operation when using the sheet, but the typewriter keys are often unnecessary and take a lot of screen space that would be better allocated for the sheet. Similarly, switching between hit and "note" keymaps is also common.

**Comment by cyberixae** [comment]
Ok. I though we already had that. At least it used to be possible to achieve that by dragging.

Perhaps the panel should be split into two parts where one is always visible and the other one can be hidden by clicking a button. However the hidden part might also later contain something else, so hiding the typewriter widget alone might not be a good way of doing this.

In some cases it may be a good technical solution to use the same widget in several views. For example, you could have a percussion view and a melody view and both of them might have the same octave selector component. This lets you surround them with different elements.

Alternatively you could have a compact octave selector/indicator elsewhere if you want to hide the entire input panel on a small screen. Or you could simply learn the keyboard shortcuts for switching octaves and then hide the entire thing.

Finally, at one point we were discussing that the typewriter might be completely useless for someone using a MIDI keyboard or some other MIDI input devices. In such cases we should probably have another, similar key mapping/indication view. One option would be to have tabs for different input methods, since they may not need to be visible at one time.

Some kind of MIDI keyboard widget might actually be useful to the user even if they don't have a physical MIDI keyboard plugged in. At least FastTracker and Zynadsubfx show one even when there are no MIDI devices attached. Obviously the user should be able to use any input device regardless of which tab is open. That said, I doubt displaying multiple alternative input methods at one time would be useful.

**Comment by cyberixae** [comment]
Actually (after listing the options and taking a shower) I am now thinking that the best solution might be to have a separate compact input panel view which would have the height of a typical tool bar. The two should probably both have some kind of toggle button in the top right corner that lets the user switch between the two. Splitting them into two separate views has the benefit that you can completely forget about the other one while designing and implementing the other.

For example Winamp had this separate compact mode and it was not the top part of the normal mode but rather a completely different thing that had some resemblance to the the controls you would use in the normal mode. See http://www.getwinamp.net/mirror/website/AOLCDN_C/WINAMP/WINAMP_WINDOWSHADE_MODE.JPG for example. I imagine they would have had lots of trouble had they tried to make the compact mode have some kind of one to one mapping with the normal mode.

**Comment by kagu** [comment]
That sounds like a good approach.
