### ISSUE TITLE
Use bzip2 with all Kunquat music and audio file formats by default

### ISSUE THREAD

**Issue by kagu** [kunquat/kunquat#596]
There is no need to have ordinary users worry about the compression format used for Kunquat files. Let's just use bzip2 by default and remove the compression suffixes of the files. We can still support loading of uncompressed or gzip-compressed Kunquat files by auto-detecting the compression format used (as we already do).

**Comment by cyberixae** [comment]
We could end up in a situation where different players support different compression standards. In this case there would be difference between which players can play which kunquat files. Ofcourse this may also be true for other aspect as kunquat develops forward but the other aspects would like be taken care of by updating to a more recent version of libkunquat.

I do not think that the suffix matters so much in this regard. What I am more worried about is supporting both gzip and bzip2 and possibly adding switching the compression in the future. It would be good if we could agree on one compression that is good enough and stick to that and perhaps event refuse to read other compressions. I would not go with something totally obscure. I guess bzip2 is not too bad but I can imagine tar.gz or zip libraries being available in more standard libraries than bzip2. Not sure though. Just a guess. Atleast I would recommend not going with anything more obsucre than bzip2.

The biggest benefit of having the compression suffix separately is that tools like "file" might be able to decompress the file before checking its magic id. However this discussion is more complex since kunquat files might anyway be identified as tar since tar files are more common that kunquat files. And also it is quite possible that tools like file would look inside the compression automatically even without the suffix since zip, gzip and bzip2 compressions are quite common these days.

**Comment by kagu** [comment]
I'm not too concerned about inconsistent support of compression formats, as I think loading Kunquat files by manually extracting the archives is cumbersome and we should provide our own interface for handling them (maybe in a separate libary akin to libvorbisfile, but that's another topic). Nevertheless, my intention is to stick to bzip2 when saving Kunquat files (perhaps I didn't communicate that clearly), and I guess it's best to reject files compressed with another format.
